name: flutter_layout

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/girl.jpeg